USE webster;

DROP TABLE IF EXISTS users;

CREATE TABLE users(
  sno INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  id INT NOT NULL,
  name VARCHAR(256) NOT NULL,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(1024) NOT NULL
) ENGINE =InnoDB;
